title: My Minimal Site
description: A minimal Jekyll example

remote_theme: vaibhavvikas/jekyll-theme-minimalistic

plugins:
  - jekyll-remote-theme

navigation:
  - title: Home
    url: /
  - title: Tabs
    url: /tabs
