title: My Minimal Site
description: A minimal Jekyll example

remote_theme: vaibhavvikas/jekyll-theme-minimalistic

color-scheme: light

plugins:
  - jekyll-remote-theme

navigation:
  - title: Home
    url: /guide
  - title: Tabs
    url: /tabs
